### ISSUE TITLE
Invalid getViewPort

### ISSUE THREAD

**Issue by JimMacBoy** [bricolsoftconsulting/GeocoderPlus#3]
Hi, 
Thanks for your great library, I do have a issue when I search for 'USA' by using this code:
<pre><code>Geocoder geocoder = new Geocoder();
geocoder.getFromLocationName("USA"); 
</pre></code>

I get back one Address with 
mLatitude=37.09024
mLongitude=-95.712891
which seems correct 

but for the mViewPort I get:
mNorthEast: mLatitude=90.0, mLongitude=180
mSouthWest: mLatitude=-90.0, mLongitude=-180
which basicly means the whole world :)

**Comment by bricolsoftconsulting** [comment]
Just merged another submit which fixed an issue with the viewport. The viewport was being overwritten with the bounds info, and the bounds info was not being set.

Please do a pull and give it a try now -- the viewport info should be correct. You can compare the info from the library with the results of the raw request below:
http://maps.googleapis.com/maps/api/geocode/json?address=USA&sensor=true&language=en_us&region=us
